In [1]:
import numpy as np # linear algebra 
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv) 
%matplotlib inline 
import matplotlib.pyplot as plt  # Matlab-style plotting 
import seaborn as sns 
color = sns.color_palette() 
import warnings 
warnings.filterwarnings('ignore') #Supress unnecessary warnings for readabilit y and cleaner presentation 
pd.set_option('display.float_format', lambda x: '%.3f' % x) #Limiting floats o utput to 3 decimal points 
 

In [2]:
train1 = pd.read_csv('C:\\Users\\Surya\\Desktop\\santander-customer-transaction-prediction\\train.csv') 
train1.head(5) 

ID_code  target  var_0  var_1  var_2  var_3  var_4  var_5  var_6  var_7  \
0  train_0       0  8.925 -6.786 11.908  5.093 11.461 -9.283  5.119 18.627   
1  train_1       0 11.501 -4.147 13.859  5.389 12.362  7.043  5.621 16.534   
2  train_2       0  8.609 -2.746 12.081  7.893 10.582 -9.084  6.943 14.616   
3  train_3       0 11.060 -2.152  8.952  7.196 12.585 -1.836  5.843 14.925   
4  train_4       0  9.837 -1.483 12.875  6.638 12.277  2.449  5.941 19.251   

    ...     var_190  var_191  var_192  var_193  var_194  var_195  var_196  \
0   ...       4.435    3.964    3.136    1.691   18.523   -2.398    7.878   
1   ...       7.642    7.721    2.584   10.952   15.431    2.034    8.127   
2   ...       2.906    9.790    1.670    1.686   21.604    3.142   -6.521   
3   ...       4.467    4.743    0.718    1.421   23.035   -1.271   -2.928   
4   ...      -1.490    9.521   -0.151    9.194   13.288   -1.512    3.927   

   var_197  var_198  var_199  
0    8.563   12.780   -1.091  
1    8.789   18.356    1.952  
2    8.268   14.722    0.397  
3   10.292   17.970   -9.000  
4    9.503   17.997   -8.810  

[5 rows x 202 columns]

In [70]:
train1.tail(5)

ID_code  target  var_0  var_1  var_2  var_3  var_4   var_5  \
199995  train_199995       0 11.488 -0.496  8.262  3.514 10.340  11.608   
199996  train_199996       0  4.915 -2.448 16.705  6.635  8.310 -10.563   
199997  train_199997       0 11.223 -5.052 10.513  5.646  9.341  -5.409   
199998  train_199998       0  9.715 -8.610 13.610  5.793 12.517   0.534   
199999  train_199999       0 10.876 -5.710 12.118  8.033 11.558   0.349   

        var_6  var_7   ...     var_190  var_191  var_192  var_193  var_194  \
199995  5.671 15.152   ...       6.141   13.230    3.990    0.939   18.025   
199996  5.880 21.594   ...       4.961    4.655    0.700    1.834   22.272   
199997  4.556 21.557   ...       4.065    5.441    3.103    4.879   23.531   
199998  6.048 17.015   ...       2.684    8.659    2.734   11.118   20.416   
199999  5.284 15.206   ...       8.984    1.689    0.128    0.377   15.210   

        var_195  var_196  var_197  var_198  var_199  
199995   -1.794    2.166    8.533   16.666  -17.866  
199996    1.734   -2.165    6.742   15.905    0.339  
199997   -1.574    1.283    8.716   13.833    4.199  
199998   -0.079    6.798   10.034   15.529  -13.900  
199999   -2.491   -2.234    8.186   12.128    0.139  

[5 rows x 202 columns]

In [3]:
test1 = pd.read_csv('C:\\Users\\Surya\\Desktop\\santander-customer-transaction-prediction\\test.csv') 
test1.head(5)

ID_code  var_0   var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  \
0  test_0 11.066   7.780 12.954  9.429 11.433 -2.381  5.849 18.267  2.134   
1  test_1  8.530   1.254 11.305  5.186  9.197 -4.012  6.020 18.632 -4.413   
2  test_2  5.483 -10.358 10.141  7.048 10.263  9.805  4.895 20.254  1.523   
3  test_3  8.537  -1.322 12.022  6.575  8.846  3.174  4.940 20.566  3.376   
4  test_4 11.706  -0.133 14.130  7.751  9.104 -8.585  6.859 10.605  2.989   

    ...     var_190  var_191  var_192  var_193  var_194  var_195  var_196  \
0   ...      -2.156   11.850   -1.430    2.451   13.711    2.467    4.365   
1   ...      10.617    8.835    0.940   10.128   15.576    0.477   -1.485   
2   ...      -0.748   10.993    1.980    2.180   12.981    2.128   -7.109   
3   ...       9.570    9.077    1.658    3.581   15.187    3.166    3.957   
4   ...       4.226    9.172    1.284    3.378   19.554   -0.286   -5.161   

   var_197  var_198  var_199  
0   10.720   15.472   -8.720  
1    9.871   19.129  -20.976  
2    7.062   19.896  -23.179  
3    9.229   13.017   -4.211  
4    7.288   13.926   -9.185  

[5 rows x 201 columns]

In [5]:
y= train1["target"]
id = test1["ID_code"]

In [6]:
test1.isnull().sum()

ID_code    0
var_0      0
var_1      0
var_2      0
var_3      0
var_4      0
var_5      0
var_6      0
var_7      0
var_8      0
var_9      0
var_10     0
var_11     0
var_12     0
var_13     0
var_14     0
var_15     0
var_16     0
var_17     0
var_18     0
var_19     0
var_20     0
var_21     0
var_22     0
var_23     0
var_24     0
var_25     0
var_26     0
var_27     0
var_28     0
          ..
var_170    0
var_171    0
var_172    0
var_173    0
var_174    0
var_175    0
var_176    0
var_177    0
var_178    0
var_179    0
var_180    0
var_181    0
var_182    0
var_183    0
var_184    0
var_185    0
var_186    0
var_187    0
var_188    0
var_189    0
var_190    0
var_191    0
var_192    0
var_193    0
var_194    0
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 201, dtype: int64

In [7]:
train1.isnull().sum()

ID_code    0
target     0
var_0      0
var_1      0
var_2      0
var_3      0
var_4      0
var_5      0
var_6      0
var_7      0
var_8      0
var_9      0
var_10     0
var_11     0
var_12     0
var_13     0
var_14     0
var_15     0
var_16     0
var_17     0
var_18     0
var_19     0
var_20     0
var_21     0
var_22     0
var_23     0
var_24     0
var_25     0
var_26     0
var_27     0
          ..
var_170    0
var_171    0
var_172    0
var_173    0
var_174    0
var_175    0
var_176    0
var_177    0
var_178    0
var_179    0
var_180    0
var_181    0
var_182    0
var_183    0
var_184    0
var_185    0
var_186    0
var_187    0
var_188    0
var_189    0
var_190    0
var_191    0
var_192    0
var_193    0
var_194    0
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 202, dtype: int64

In [9]:
print (corr['target'].sort_values(ascending=False)[:15], '\n') #top 15 values
print ('----------------------')
print (corr['target'].sort_values(ascending=False)[-5:]) #last 5 values`

(target    1.000
var_6     0.067
var_110   0.064
var_53    0.063
var_26    0.062
var_22    0.061
var_99    0.058
var_190   0.056
var_2     0.056
var_133   0.055
var_0     0.052
var_1     0.050
var_179   0.050
var_40    0.050
var_184   0.048
Name: target, dtype: float64, '\n')
----------------------
var_76    -0.062
var_146   -0.064
var_12    -0.069
var_139   -0.074
var_81    -0.081
Name: target, dtype: float64


In [10]:
train1.get_dtype_counts()

float64    200
int64        1
object       1
dtype: int64

In [6]:

train1.drop(["ID_code", "target"], axis=1, inplace=True)
test1.drop(["ID_code"], axis=1, inplace=True)

In [7]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
import numpy as np
X_scaled = preprocessing.scale(train1)
X_scaled

array([[-0.57710174, -1.27373702,  0.45170728, ..., -0.37396811,
        -1.02639785,  0.21413482],
       [ 0.26995857, -0.62213756,  1.19036045, ..., -0.12939961,
         0.82541712,  0.50568523],
       [-0.68111341, -0.2760664 ,  0.51698836, ..., -0.69514059,
        -0.38144932,  0.35668144],
       ...,
       [ 0.17870987, -0.84546901, -0.07667568, ..., -0.20904171,
        -0.67680579,  0.72102365],
       [-0.31746727, -1.72398014,  1.09630117, ...,  1.22180338,
        -0.11352617, -1.01298853],
       [ 0.06456676, -1.00810962,  0.53130173, ..., -0.78389704,
        -1.24290845,  0.33196403]])

In [8]:
X_scaled2 = preprocessing.scale(test1)
X_scaled2

array([[ 0.13398157,  2.32744611,  0.85278996, ...,  1.96282758,
        -0.13194481, -0.52635716],
       [-0.70086986,  0.71242283,  0.22675581, ...,  1.04133974,
         1.08355968, -1.70501041],
       [-1.70448957, -2.16157859, -0.21517745, ..., -2.00958206,
         1.33825359, -1.91690508],
       ...,
       [ 0.32181655,  0.96551038,  0.18981414, ...,  0.30499646,
        -1.35562556, -1.83004692],
       [ 0.9601723 ,  0.27492737,  1.12037979, ..., -0.87363057,
        -2.35838103,  0.29178474],
       [-0.06333737,  0.84921287, -0.18214635, ...,  1.54779971,
        -0.51024652, -0.4291995 ]])

In [9]:
%matplotlib inline

In [10]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(X_scaled)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [12]:
from sklearn.decomposition import PCA
pca1 = PCA(n_components=2)
principalComponents1 = pca1.fit_transform(X_scaled2)
principalDff = pd.DataFrame(data = principalComponents1
             , columns = ['principal component 1', 'principal component 2'])

In [13]:
y_train = y
X_train = X_scaled
X_test1 = X_scaled2
y_test = y

In [14]:

from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train,y_train)

#
y_pred=logreg.predict(X_test1)

In [15]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn import metrics
cnf_matrix1 = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix1

array([[174407,   5495],
       [ 19475,    623]], dtype=int64)

In [17]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

('Accuracy:', 0.87515)
('Precision:', 0.10183066361556065)
('Recall:', 0.030998109264603443)


In [13]:
##submission
sub_df = pd.DataFrame({"ID_code":id})
sub_df["target"] = y_pred
sub_df.to_csv("sub4.csv", index=False)

In [18]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)

clf.fit(X_train,y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(5, 2),
              learning_rate='constant', learning_rate_init=0.001,
              max_iter=200, momentum=0.9, n_iter_no_change=10,
              nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [29]:
ypred = clf.predict(X_test1)
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
[coef.shape for coef in clf.coefs_]


[(200L, 5L), (5L, 2L), (2L, 1L)]

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, ypred)
print(confusion_matrix)

[[174127   5775]
 [ 19449    649]]


In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93    179902
           1       0.10      0.03      0.05     20098

   micro avg       0.87      0.87      0.87    200000
   macro avg       0.50      0.50      0.49    200000
weighted avg       0.82      0.87      0.84    200000



In [25]:

print('MLP classifier on test set: {:.2f}'.format(logreg.score(X_test1, y_test)))

MLP classifier on test set: 0.88


In [26]:
##submission
sub_df = pd.DataFrame({"ID_code":id})
sub_df["target"] = ypred
sub_df.to_csv("sub6.csv", index=False)

In [27]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
#from sklearn.cross_validation import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
  

       
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test1, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=3, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini 
      
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test1, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 
  
  
# Function to make predictions 
def prediction(X_test1, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test1) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 
      
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
  
# Driver code 
def main(): 
      
     
    clf_gini = train_using_gini(X_train, X_test1, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test1, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test1, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test1, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 
      
      
# Calling main function 
if __name__=="__main__": 
    main() 

Results Using Gini Index:
Predicted values:
[0 0 0 ... 0 0 0]
('Confusion Matrix: ', array([[179902,      0],
       [ 20098,      0]], dtype=int64))
('Accuracy : ', 89.95100000000001)
('Report : ', u'              precision    recall  f1-score   support\n\n           0       0.90      1.00      0.95    179902\n           1       0.00      0.00      0.00     20098\n\n   micro avg       0.90      0.90      0.90    200000\n   macro avg       0.45      0.50      0.47    200000\nweighted avg       0.81      0.90      0.85    200000\n')
Results Using Entropy:
Predicted values:
[0 0 0 ... 0 0 0]
('Confusion Matrix: ', array([[179743,    159],
       [ 20082,     16]], dtype=int64))
('Accuracy : ', 89.87950000000001)
('Report : ', u'              precision    recall  f1-score   support\n\n           0       0.90      1.00      0.95    179902\n           1       0.09      0.00      0.00     20098\n\n   micro avg       0.90      0.90      0.90    200000\n   macro avg       0.50      0.50      0

In [28]:
##submission
sub_df = pd.DataFrame({"ID_code":id})
sub_df["target"] = ypred
sub_df.to_csv("sub7.csv", index=False)